# Generated by Django 4.2 on 2023-05-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
